- hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/dns.vault
    - group_vars/ssl.vault
  
  roles:
    - commons
    - optimization
    - network
    - mysql
    - mariadb
    - phpmyadmin
    - postgresql
    - pgadmin
    - mongodb
    - mongoexpress
    - redis
    - rebrow
    - wordpress
    - joomla
    - drupal
    - magento
    - moodle
    - gitlab
    - gitea
    - rancher
    - rabbitmq
    - postalserver
    - portus
    - jitsi
    - kafka
    