- hosts: all
  become: true
  gather_facts: yes
  roles:
    # First connect
    - commons
    - optimization
    - network

    # Databases
    - mysql
    - phpmyadmin
    - postgresql
    - pgadmin

    # CMS
    - wordpress
    - joomla

    # Apps
    - rancher
    - redis
    - rabbitmq