- hosts: all
  become: true
  gather_facts: yes
  roles:
    - commons
    - optimization
    - mysql
    - phpmyadmin
    - postgresql
    - pgadmin
    - wordpress
    - joomla
    - rancher
    - rabbitmq