- hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/dns.vault
    - group_vars/ssl.vault
    
  roles:
    # First connect
    - commons
    - optimization
    - network

    # Databases
    - mysql
    - phpmyadmin
    - postgresql
    - pgadmin

    # CMS
    - wordpress
    - joomla

    # Apps
    - rancher
    - redis
    - rabbitmq