# Cloudboz - Gitea Install
- name: "Install Gitea"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitea_docker_name }}"
    image: "{{ gitea_docker_name }}:{{ gitea_docker_tag }}"
    networks:
      - name: cloudboz-network
    restart_policy: always
    volumes:
      - "/cloudboz/{{ gitea_docker_name }}-data:/data"
      - "/cloudboz/{{ gitea_docker_name }}-data/timezone:/etc/timezone:ro"
      - "/cloudboz/{{ gitea_docker_name }}-data/localtime:/etc/localtime:ro"
    ports:
      - "{{ gitea_docker_ports }}:3000"
      - "{{ gitea_ssh_docker_ports }}:22"
    tags:
      - install-gitea

# Cloudboz - Gitea Uninstall    
- name: "Uninstall gitea"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitea_docker_name }}"
    state: absent
  tags:
    - uninstall-gitea
