---
# CloudBoz - Default users
- name: "create user '{{ cloudboz_username }}'"
  user:
    name: "{{ cloudboz_username }}"
    password: "{{ cloudboz_password }}"
    groups: sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ cloudboz_username }}"
  tags:
    - commons-install

- name: "replace sshd_config for pass & pubkey auth"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.From }}'
    line: '{{ item.To }}'
  with_items:
    - { From: 'PasswordAuthentication no', To: '{{ pass_auth }}'}
    - { From: 'PubkeyAuthentication no', To: '{{ pubkey_auth }}'}
  tags:
    - commons-install

- name: "restart sshd service"
  systemd:
    state: restarted
    name: sshd
  tags:
    - commons-install

# CloudBoz - Update & upgrade systems
- name: "update and upgrade systems"
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
  tags:
    - commons-install

# CloudBoz - Install recommended apps
- name: "install systems dependencies"
  apt:
    name:
      - apt-transport-https
      - gnupg
      - gnupg-agent
      - ca-certificates
      - openssl
      - curl
      - software-properties-common
      - build-essential
      - net-tools
      - htop
      - ncdu
      - vim
      - nano
      - ufw
      - git
      - zip
      - unzip
      - rsync
      - sshpass
      - whois
      - snapd
    state: present
  tags:
    - commons-install

# CloudBoz - Docker Install
- name: "add gpg docker"
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present
  tags:
    - commons-install

- name: "add docker repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  tags:
    - commons-install

- name: "install docker"
  apt: name={{ item }} update_cache=false
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - commons-install

- name: "start systemd docker"
  systemd:
    state: started
    name: docker
    enabled: true
  tags:
    - commons-install

- name: "add user permissions"
  shell: "usermod -aG docker {{ ansible_user }}"
  tags:
    - commons-install

# CloudBoz - Installs Docker SDK
- name: "install python package manager"
  apt:
    name: python3-pip
  tags:
    - commons-install

- name: "install python sdk"
  become_user: "{{ ansible_user }}"
  pip:
    name:
      - docker
      - docker-compose
  tags:
    - commons-install
        
- name: "check current docker-compose version"
  command: docker-compose --version
  register: docker_compose_vsn
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - commons-install

- set_fact:
    docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when:
    - docker_compose_vsn.stdout is defined
  tags:
    - commons-install

- name: "install or upgrade docker-compose"
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
    force: yes
  when: >
    docker_compose_current_version is not defined
    or docker_compose_current_version is version(docker_compose_version, '<')
  tags:
    - commons-install

# CloudBoz - Kernel optimization
- name: "config kernel at /etc/sysctl.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/sysctl.conf
  with_items:
    - cb-sysctl.conf
  tags:
    - commons-install

- name: "reload kernel at /etc/sysctl.conf"
  shell: sysctl -p
  args:
    executable: /bin/bash
  tags:
    - commons-install

- name: "config ulimit at /etc/security/limits.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/security/limits.conf
  with_items:
    - cb-limits.conf
  tags:
    - commons-install

# CloudBoz - Swap memory
- name: "create swap at /swapfile"
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }} creates="{{ swap_file_path }}"
  tags:
    - commons-install

- name: "change permissions at /swapfile"
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
  tags:
    - commons-install

- name: "checking type at /swapfile"
  command: file {{ swap_file_path }}
  register: swapfile
  tags:
    - commons-install

- name: "make swap at /swapfile"
  command: "sudo mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - commons-install

- name: "write swap entry in fstab"
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - commons-install

- name: "mount /swapfile"
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - commons-install