---
# CloudBoz - Default configurations
- name: "replace sshd_config for pass & pubkey auth"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.From }}'
    line: '{{ item.To }}'
  with_items:
    - { From: 'PasswordAuthentication no', To: '{{ pass_auth }}'}
    - { From: 'PubkeyAuthentication no', To: '{{ pubkey_auth }}'}
  tags:
    - install-commons

- name: "restart sshd service"
  systemd:
    state: restarted
    name: sshd
  tags:
    - install-commons

# CloudBoz - Update & upgrade systems
- name: "update and upgrade systems"
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
  tags:
    - install-commons

# CloudBoz - Install recommended apps
- name: "install systems dependencies"
  apt:
    name:
      - apt-transport-https
      - gnupg
      - gnupg-agent
      - ca-certificates
      - openssl
      - curl
      - software-properties-common
      - build-essential
      - net-tools
      - htop
      - ncdu
      - vim
      - nano
      - ufw
      - git
      - zip
      - unzip
      - rsync
      - sshpass
      - whois
      - snapd
    state: present
  tags:
    - install-commons

# CloudBoz - Docker Install
- name: "add gpg docker"
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present
  tags:
    - install-commons

- name: "add docker repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  tags:
    - install-commons

- name: "install docker"
  apt: name={{ item }} update_cache=false
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - install-commons

- name: "start systemd docker"
  systemd:
    state: started
    name: docker
    enabled: true
  tags:
    - install-commons

# CloudBoz - Installs Docker SDK
- name: "install python package manager"
  apt:
    name: python3-pip
  tags:
    - install-commons

- name: "install python sdk"
  become_user: "{{ ansible_user }}"
  pip:
    name:
      - docker
      - docker-compose
  tags:
    - install-commons

- name: "add user permissions"
  shell: "usermod -aG docker {{ ansible_user }}"
  tags:
    - install-commons

# CloudBoz - Kernel optimization
- name: "config kernel at /etc/sysctl.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/sysctl.conf
  with_items:
    - cb-sysctl.conf
  tags:
    - install-commons

- name: "reload kernel at /etc/sysctl.conf"
  shell: sysctl -p
  args:
    executable: /bin/bash
  tags:
    - install-commons

- name: "config ulimit at /etc/security/limits.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/security/limits.conf
  with_items:
    - cb-limits.conf
  tags:
    - install-commons

# CloudBoz - Swap memory
- name: "create swap at /swapfile"
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }} creates="{{ swap_file_path }}"
  tags:
    - install-commons

- name: "change permissions at /swapfile"
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
  tags:
    - install-commons

- name: "checking type at /swapfile"
  command: file {{ swap_file_path }}
  register: swapfile
  tags:
    - install-commons

- name: "make swap at /swapfile"
  command: "sudo mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - install-commons

- name: "write swap entry in fstab"
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - install-commons

- name: "mount /swapfile"
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - install-commons