---
# CloudBoz - tasks file for rabbitmq install
- name: "install rabbitmq"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rabbitmq_app_name }}"
    image: "{{ rabbitmq_docker_image }}:{{ rabbitmq_docker_tag }}"
    volumes:
      - "/home/{{ ansible_user }}/{{ rabbitmq_app_name }}-data:/var/lib/rabbitmq:rw"
    restart_policy: always
    networks:
      - name: cloudboz-network
    ports:
      - "{{ rabbitmq_ui_docker_ports }}:15672" # HTTP management UI
      - "{{ rabbitmq_amqp_docker_ports }}:5672" # AMQP protocol port
    privileged: true
    env:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_docker_env_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_docker_env_password }}"
  tags:
    - install-rabbitmq

# CloudBoz - rabbitmq Uninstall    
- name: "Remove Rabbitmq Container"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rabbitmq_app_name }}"
    state: absent
  tags:
    - uninstall-rabbitmq