---
# CloudBoz - tasks file for rabbitmq install
- name: "Config rabbitmq"
  template:
    src: rabbitmq.conf.j2
    dest: "/home/cloudboz/{{ rabbitmq_app_name }}-config/rabbitmq.config"
  tags:
    - rabbitmq-install

- name: "install rabbitmq"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ rabbitmq_app_name }}"
    image: "{{ rabbitmq_docker_image }}:{{ rabbitmq_docker_tag }}"
    volumes:
      - "/home/cloudboz/{{ rabbitmq_app_name }}-config:/etc/rabbitmq"
      - "/home/cloudboz/{{ rabbitmq_app_name }}-data:/var/lib/rabbitmq:rw"
    restart_policy: always
    ports:
      - "{{ rabbitmq_docker_ports }}:15672"
    env:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_docker_env_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_docker_env_password }}"
  tags:
    - rabbitmq-install