# CloudBoz - GitLab Install
- name: "install gitlab"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitlab_docker_name }}"
    image: "{{ gitlab_docker_image }}:{{ gitlab_docker_tag }}"
    networks:
      - name: cloudboz-network
    volumes:
      - "/cloudboz/{{ gitlab_docker_name }}-data/config:/etc/gitlab"
      - "/cloudboz/{{ gitlab_docker_name }}-data/logs:/var/log/gitlab"
      - "/cloudboz/{{ gitlab_docker_name }}-data/data:/var/opt/gitlab"
    restart_policy: always
    shm_size: "256m"
    hostname: "{{ gitlab_docker_domain }}"
    ports:
      - "{{ gitlab_docker_ports_http }}:80"
      - "{{ gitlab_docker_ports_https }}:443"
      - "{{ gitlab_docker_ports_ssh }}:22"
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '{{ gitlab_docker_domain }}'
  tags:
    - install-gitlab

# CloudBoz - GitLab Firewall Install
- name: "'{{ ufw_rule }}' port '{{ gitlab_docker_ports_http }},{{ gitlab_docker_ports_https }},{{ gitlab_docker_ports_ssh }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ gitlab_docker_ports_http | quote }}"
    - "{{ gitlab_docker_ports_https | quote }}"
    - "{{ gitlab_docker_ports_ssh | quote }}"
  tags:
    - install-gitlab

# CloudBoz - GitLab Uninstall
- name: "uninstall gitlab"
  become_user: "{{ ansible_user }}"
  community.docker.docker_container:
    name: "{{ gitlab_docker_name }}"
    state: absent
  tags:
    - uninstall-gitlab

# CloudBoz - GitLab Firewall Uninstall
- name: "'{{ ufw_rule }}' port '{{ gitlab_docker_ports_http }},{{ gitlab_docker_ports_https }},{{ gitlab_docker_ports_ssh }}'"
  community.general.ufw:
    rule: "{{ ufw_rule }}"
    port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - "{{ gitlab_docker_ports_http | quote }}"
    - "{{ gitlab_docker_ports_https | quote }}"
    - "{{ gitlab_docker_ports_ssh | quote }}"
  tags:
    - uninstall-gitlab

# CloudBoz - GitLab Uninstall with Data
- name: "uninstall gitlab data"
  become_user: "{{ ansible_user }}"
  shell: "sudo rm -fr /cloudboz/{{ gitlab_docker_name }}-data/config:/etc/gitlab; sudo rm -fr /cloudboz/{{ gitlab_docker_name }}-data/logs:/var/log/gitlab; sudo rm -fr /cloudboz/{{ gitlab_docker_name }}-data/data:/var/opt/gitlab"
  tags:
    - uninstall-gitlab-data