# MYSQL ENV
mysql_docker_name: mysql
mysql_docker_image: mysql
mysql_docker_tag: latest
mysql_docker_ports: 3306
mysql_docker_env_root_password: mysql-root-pass # default user is a root
mysql_docker_env_database: mysql-db-test # create a new database
mysql_docker_env_user: mysql-user-test # create a new user
mysql_docker_env_password: mysql-pass-test # create a new password
